AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PDCHazardsAuthToken:
    Type: String
    NoEcho: true

  EarthdataUsername:
    Type: String

  EarthdataPassword:
    Type: String
    NoEcho: true

# TODO: Add scheduled trigger for lambda
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          PDC_HAZARDS_AUTH_TOKEN: !Ref PDCHazardsAuthToken
          EARTHDATA_USERNAME: !Ref EarthdataUsername
          EARTHDATA_PASSWORD: !Ref EarthdataPassword
      Code: src/
      Handler: main.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python3.9
      Timeout: 900
