name: Deploy HyP3 Flood Monitoring Production

on:
  push:
    branches:
      - main

concurrency: deploy-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          HYP3_URL: https://hyp3-pdc.asf.alaska.edu
          S3_TARGET_BUCKET: hyp3-pdc-data
          S3_TARGET_PREFIX: PDC
          STACK_NAME: hyp3-flood-monitoring
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          PDC_HAZARDS_AUTH_TOKEN: ${{ secrets.PDC_HAZARDS_AUTH_TOKEN }}
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
          PROCESSING_STATE: DISABLED

  call-bump-version-workflow:
    needs: deploy
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.8.2
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
