name: Deploy HyP3 Flood Monitoring Test

on:
  push:
    branches:
      - develop

concurrency: deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          PDC_HAZARDS_AUTH_TOKEN: ${{ secrets.PDC_HAZARDS_AUTH_TOKEN }}
          HYP3_URL: https://hyp3-test-api.asf.alaska.edu
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
          S3_TARGET_BUCKET: hyp3-nasa-disasters
          S3_TARGET_PREFIX: PDC-test
          STACK_NAME: hyp3-flood-monitoring-test
