name: Generate Stats

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

env:
  HYP3_URL: https://hyp3-test-api.asf.alaska.edu
  EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
  EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
  GENERATE_STATS_AWS_ACCESS_KEY_ID: ${{ secrets.GENERATE_STATS_AWS_ACCESS_KEY_ID }}
  GENERATE_STATS_AWS_SECRET_ACCESS_KEY: ${{ secrets.GENERATE_STATS_AWS_SECRET_ACCESS_KEY }}

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: scripts
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.GENERATE_STATS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.GENERATE_STATS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install
        run: |
          python -m pip install --upgrade pip && \
          python -m pip install -r scripts/requirements.txt
      - name: Get stats
        run: PYTHONPATH=${PWD}/hyp3-floods/src python scripts/get_stats.py --upload
